# CONTOH FORMAT
# https://blog.vpngame.com/openwrt/kumpulan-daftar-format-akun-untuk-openclash/
proxies:
- name: Vmess WS
  # interface-name: eth1
  type: vmess
  server: SERVER.COM
  port: 443
  uuid: UUID
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
  servername: SERVER.COM
  network: ws
  ws-opts:
    path: /PATH
    headers:
      Host: SERVER.COM

- name: Trojan WS
  # interface-name: eth1
  server: SERVER.COM
  port: 443
  type: trojan
  password: PASSWORD
  skip-cert-verify: true
  sni: SERVER.COM
  network: ws
  ws-opts:
    path: /PATH
    headers:
      Host: SERVER.COM
  udp: true